const controls = [
  {
    field_name: "Autocomplete",
    type: "autocomplete",
    label: "Autocomplete",
    className: "form-control",
    name: "autocomplete",
    requireValidOption: true,
    required: false,
    values: [
      {
        label: "Option 1",
        value: "option-1",
      },
      {
        label: "Option 2",
        value: "option-2",
      },
      {
        label: "Option 3",
        value: "option-3",
      },
    ],
  },
  {
    field_name: "Button",
    type: "button",
    label: "Button",
    subtype: ["submit", "reset", "button"],
    className: "btn",
    name: "button",
    value: "Submit",
  },
  {
    field_name: "Checkbox Group",
    type: "checkbox-group",
    label: "Checkbox Group",
    description: "This is some helptext",
    toggle: true,
    inline: true,
    className: "checkbox",
    name: "checkbox-group",
    values: [
      {
        label: "Option 1",
        value: "option-1",
        selected: true,
      },
      {
        label: "Option 2",
        value: "option-2",
      },
      {
        label: "Option 3",
        value: "Option 4",
      },
    ],
  },
  {
    field_name: "Date Field",
    type: "date",
    required: true,
    label: "Date Field",
    description: "this is date field",
    placeholder: "ENter the date",
    className: "form-control",
    name: "date",
  },
  {
    field_name: "File Upload",
    type: "file",
    label: "File Upload",
    description: "THis is file",
    placeholder: "File",
    className: "form-control",
    name: "file",
    subtype: "file",
    multiple: true,
  },
  {
    field_name: "Header",
    type: "header",
    subtype: "h1",
    label: "Header",
    className: "heading",
  },
  {
    field_name: "Hidden Input",
    type: "hidden",
    name: "hidden",
    value: "test",
  },
  {
    field_name: "Number",
    type: "number",
    label: "Number",
    description: "asjdkasldjlq",
    placeholder: "jkl",
    className: "jkl",
    name: "jkl",
    value: "jkl",
    min: "2",
    max: "3",
    step: "1",
  },
  {
    field_name: "Paragraph",
    type: "paragraph",
    subtype: "p",
    label: "Paragraph",
    className: "askldjaslkdj",
  },
  {
    field_name: "Radio Group",
    type: "radio-group",
    required: true,
    label: "Radio Group",
    description: "askldjasldjkl",
    inline: true,
    className: "kasdjklasdjklj",
    name: "radio-group-1623930582220",
    values: [
      {
        label: "Option 1",
        value: "option-1",
      },
      {
        label: "Option 2",
        value: "option-2",
      },
      {
        label: "Option 3",
        value: "option-3",
      },
    ],
  },
  {
    field_name: "Select",
    type: "select",
    required: true,
    label: "Select",
    description: "asdklasjkld",
    placeholder: "kdj",
    className: "klj",
    name: "klj",
    multiple: true,
    values: [
      {
        label: "Option 1",
        value: "option-1",
        selected: true,
      },
      {
        label: "Option 2",
        value: "option-2",
      },
      {
        label: "Option 3",
        value: "option-3",
      },
    ],
  },
  {
    field_name: "Text Field",
    type: "text",
    required: true,
    label: "Text Field",
    description: "kljaskldjaskldjkl",
    placeholder: "kljkl",
    className: "form-control",
    name: "text-1623930653929",
    value: "askljdklasjdklasjdklasjkldjkl",
    subtype: ["text", "password", "email", "color", "tel"],
    maxlength: "15",
  },
  {
    field_name: "Text Area",
    type: "textarea",
    required: true,
    label: " Text Area",
    description: "asjkdklasdjkl",
    placeholder: "jkl",
    className: "jkl",
    name: "jkl",
    value: "kljkljkljkljkljkl",
    subtype: ["textarea", "tinymce", "quill"],
  },
];
export default controls;
