const controls = [
  {
    component: "Autocomplete",
    field_name: "Autocomplete",
    type: "autocomplete",
    label: "Autocomplete",
    className: "form-control",
    name: "autocomplete",
    placeholder: "This is the placeholder",
    requireValidOption: true,
    required: true,
    values: [
      {
        label: "Option 1",
        value: "option-1",
      },
      {
        label: "Option 2",
        value: "option-2",
      },
      {
        label: "Option 3",
        value: "option-3",
      },
    ],
  },
  {
    component: "ButtonField",
    field_name: "Button",
    type: "button",
    label: "Button",
    subtype: ["submit", "reset", "button"],
    className: "btn btn-info",
    name: "button",
    value: "Submit",
  },
  {
    component: "CheckBoxGroupField",
    field_name: "Checkbox Group",
    type: "checkbox-group",
    label: "Checkbox Group",
    description: "This is some helptext",
    toggle: true,
    inline: true,
    className: "checkbox",
    name: "checkbox-group",
    required: false,
    values: [
      {
        label: "Option 1",
        value: "option-1",
        checked: true,
      },
      {
        label: "Option 2",
        value: "option-2",
      },
      {
        label: "Option 3",
        value: "Option 4",
      },
    ],
  },
  {
    component: "DateField",
    field_name: "Date Field",
    type: "date",
    required: true,
    label: "Date Field",
    description: "this is date field",
    placeholder: "ENter the date",
    className: "form-control",
    name: "date",
  },
  {
    component: "FileUploadField",
    field_name: "File Upload",
    type: "file",
    label: "File Upload",
    description: "THis is file",
    placeholder: "File",
    className: "form-control",
    name: "file",
    multiple: true,
    required: true,
  },
  {
    component: "HeadingField",
    field_name: "Header",
    type: "header",
    subType: "h1",
    label: "Header",
    className: "heading",
  },
  {
    component: "HiddenField",
    field_name: "Hidden Input",
    type: "hidden",
    name: "hidden",
    value: "test",
  },
  {
    component: "NumberField",
    field_name: "Number",
    type: "number",
    label: "Number",
    description: "This is number field",
    placeholder: "This is placeholder",
    className: "form-control",
    name: "number",
    value: 25,
    min: 2,
    max: 3,
    step: 1,
    title: "number",
  },
  {
    component: "ParagraphField",
    field_name: "Paragraph",
    type: "paragraph",
    label: "Paragraph",
    className: "paragraph",
  },
  {
    component: "RadioGroupField",
    field_name: "Radio Group",
    type: "radio-group",
    required: true,
    label: "Radio Group",
    description: "This is Description",
    inline: true,
    className: "form-check-input",
    name: "radio-group",
    values: [
      {
        label: "Option 1",
        value: "option-1",
      },
      {
        label: "Option 2",
        value: "option-2",
      },
      {
        label: "Option 3",
        value: "option-3",
      },
    ],
  },
  {
    component: "SelectField",
    field_name: "Select",
    type: "select",
    required: true,
    label: "Select Dropdown",
    description: "this is description",
    placeholder: "This is placeholder",
    className: "",
    name: "select",
    multiple: true,
    values: [
      {
        label: "Option 1",
        value: "option-1",
      },
      {
        label: "Option 2",
        value: "option-2",
      },
      {
        label: "Option 3",
        value: "option-3",
        selected: true,
      },
    ],
  },
  {
    component: "TextField",
    field_name: "Text Field",
    type: "email",
    required: true,
    label: "Text Field",
    description: "kljaskldjaskldjkl",
    placeholder: "kljkl",
    className: "form-control",
    name: "text-1623930653929",
    value: "askljdklasjdklasjdklasjkldjkl",
    subtype: ["text", "password", "email", "color", "tel"],
    maxLength: "255",
  },
  {
    component: "TextAreaField",
    field_name: "Text Area",
    type: "textarea",
    required: true,
    label: "Text Area",
    description: "asjkdklasdjkl",
    placeholder: "jkl",
    className: "jkl",
    name: "jkl",
    value: "kljkljkljkljkljkl",
    subtype: ["textarea", "tinymce", "quill"],
    maxlength: 200,
    rows: 5,
    title: "This is help text",
  },
];
export default controls;
